# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               git kitty
tagline:             Hacking through NYC
description:         'An attempt to organize notes, thoughts, explorations, and solutions in one place where all can see.'
url:                 http://gitkitty.com
baseurl:             /
paginate:            5
github_repo:         https://github.com/RDFroeber/gitkitty-jekyll

# About/contact
author:
  name:              Raleigh D. Froeber
  email:             raleigh@gitkitty.com
  twitter:           gitkitty
  github:            rdfroeber

# Custom vars
version:             0.1.0