# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               git kitty
tagline:             Hacking through NYC
description:         I like building things.
url:                 http://gitkitty.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Raleigh D. Froeber
  email:             raleigh@gitkitty.com
  twitter:           gitkitty
  github:            rdfroeber

# Custom vars
version:             1.0.0